# Generated by Django 4.0.2 on 2022-04-04 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file1',
            field=models.FileField(default=True, upload_to=''),
            preserve_default=False,
        ),
    ]
