# Generated by Django 4.0.2 on 2022-04-05 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_message_file1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='file1',
        ),
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
