# Generated by Django 4.0.2 on 2022-04-05 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_message_file1_message_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(default='message'),
        ),
    ]
