# Generated by Django 4.0.2 on 2022-04-07 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_message_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='link',
            field=models.CharField(default=True, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=80),
        ),
    ]
