# Generated by Django 4.0.2 on 2022-04-07 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_topic_link_alter_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='link2',
            field=models.CharField(default=True, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='link3',
            field=models.CharField(default=False, max_length=250),
            preserve_default=False,
        ),
    ]
