# Generated by Django 4.0.2 on 2022-04-07 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_topic_link2_topic_link3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='link',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='topic',
            name='link2',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='topic',
            name='link3',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
