# Generated by Django 4.0.2 on 2022-04-07 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_topic_link_alter_topic_link2_alter_topic_link3'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='link',
            new_name='link1',
        ),
    ]
